chore: disable old Formula in favor of Cask
The oastools Formula has been disabled to guide users to the new Cask
installation method. As of v1.9.5+, oastools is distributed as a
Homebrew Cask instead of a Formula.

Users attempting to upgrade will see:
  Error: erraggy/oastools/oastools has been disabled because the cask should be used now instead!

The Cask can be installed with:
  brew install oastools
  # or explicitly:
  brew install --cask oastools

Related: planning/homebrew-cask-migration.md in oastools repository